### ISSUE TITLE
Old data is not saved on entity removal

### ISSUE THREAD

**Issue by TwanVermeulen** [madmis/ActivityLogBundle#7]
Hi @madmis,

As you might have noticed I'm implementing your bundle. Thanks for creating this tool! 

During the implementation I faced the following issue:
When an entity is removed, no (old/new) data is stored in the log table. 
If the entity is hard deleted, it isn't (easily) possible to display information about the removed entity.

My suggestion is store all the versioned properties in the old_data column upon entity removal. 

I've implemented this functionality in a custom logger. Do you want me to create a PR for this?

**Comment by madmis** [comment]
Hi, @TwanVermeulen,

There was some promblems with implementing this functionality, so i leave implemetation for other time.

But if this functionality implemented, sure, create pull request. I will merge it.

Also, if you want, i can add you to this repository as collaborators (because now i have no time quickly react for bugs and other requests). So you can make changes without waiting any approves. I think together we can make this bundle better :)

**Comment by TwanVermeulen** [comment]
That sounds great. It would be nice if you can add me as a collaborator. I will do some PRs to improve this bundle even more :) I have to clean up the code a bit but I can do a first PR in the beginning of next week.

**Comment by madmis** [comment]
I'm add you. You should get invitation.

I have updated [demo application](https://github.com/madmis/ActivityLogBundle-Demo) for bundle (add docker and create more actions for create log entries).

**Comment by madmis** [comment]
@TwanVermeulen, i have implementation for this issue. I will create branch and pull it there, so you can review it and compare with your implementation.

You can make the same and we can choose better solution.

**Comment by madmis** [comment]
https://github.com/madmis/ActivityLogBundle/compare/delete-save-more-data?expand=1

**Comment by madmis** [comment]
Pull request merged. Old data will be saved now.
